<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.6 on win32)" generated="20200203 15:32:24.558" rpa="false">
<suite id="s1" name="CorrectCredentialsToTestDataDriverExcel" source="C:\Users\fabio.olivieri\RobotTesting\RobotTests\UITests\Login\CorrectCredentialsToTestDataDriverExcel.robot">
<test id="s1-t1" name="TestLoginWithExcel">
<kw name="TestCredencialesCorrectas">
<arguments>
<arg>${eUsuario}</arg>
<arg>${eContrasenia}</arg>
<arg>${eTerminal}</arg>
</arguments>
<msg timestamp="20200203 15:32:24.726" level="FAIL">Variable '${eUsuario}' not found.</msg>
<status status="FAIL" starttime="20200203 15:32:24.726" endtime="20200203 15:32:24.726"></status>
</kw>
<status status="FAIL" starttime="20200203 15:32:24.726" endtime="20200203 15:32:24.726" critical="yes">Variable '${eUsuario}' not found.</status>
</test>
<kw name="Cerrar Todo" library="General" type="teardown">
<kw name="Close All Browsers" library="SeleniumLibrary">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20200203 15:32:24.726" endtime="20200203 15:32:24.726"></status>
</kw>
<status status="PASS" starttime="20200203 15:32:24.726" endtime="20200203 15:32:24.726"></status>
</kw>
<status status="FAIL" starttime="20200203 15:32:24.559" endtime="20200203 15:32:24.726"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="CorrectCredentialsToTestDataDriverExcel">CorrectCredentialsToTestDataDriverExcel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200203 15:32:24.726" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\fabio.olivieri\RobotTesting\RobotTests\UITests\Login\../../../ExternalFiles/ParametrosVerificarCredencialesIncorrectas.xlsx but file does not exist.</msg>
</errors>
</robot>
